cache:
  - C:\strawberry

install:
  - if not exist "C:\strawberry" choco install strawberryperl -y
  - set PATH=C:\strawberry\c\bin;C:\strawberry\perl\site\bin;C:\strawberry\perl\bin;%PATH%
  - cd %APPVEYOR_BUILD_FOLDER%
  - cpanm -n JSON::PP Hook::AfterRuntime Sub::Util match::simple
  - cpanm -n Text::sprintfn Dist::Inkt::Profile::TOBYINK

build_script:
  - distinkt-dist --TRAVIS --targetdir=build
  - cd build
  - perl Makefile.PL
  - gmake

test_script:
  - gmake test
