language: perl
matrix:
  include:
    - perl: "dev"
    - perl: "dev-thr"
    - perl: "5.30"
    - perl: "5.30-thr"
    - perl: "5.28"
    - perl: "5.26"
      dist: trusty
    - perl: "5.24"
      dist: trusty
    - perl: "5.22"
      dist: trusty
    - perl: "5.20"
      dist: trusty
    - perl: "5.18"
      dist: trusty
    - perl: "5.16"
      dist: trusty
    - perl: "5.14"
      dist: trusty
    - perl: "5.12"
      dist: trusty
    - perl: "5.12-thr"
      dist: trusty
    - perl: "5.10"
      dist: trusty
    - perl: "5.8.9"
      dist: trusty
    - perl: "5.8.1"
      dist: trusty
    - perl: "blead"
  allow_failures:
    - perl: "5.8.1"
    - perl: "blead"
before_install:
  - export DIST_INKT_PROFILE="Dist::Inkt::Profile::TOBYINK"
  - eval $(curl https://travis-perl.github.io/init) --auto
install:
  - cpan-install --toolchain
  - cpan-install --deps
